from . import accont_move
from . import accont_move_line
from . import calendar_event
from . import crm_lead
from . import crm_lead_fuente
from . import loyalty_program
from . import product_pricelist
from . import project_task
from . import res_partner
from . import res_partner_category
from . import sale_order
from . import sale_order_line
from . import product_packaging
from . import product_search
